# Generated by Django 3.2.20 on 2023-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
