# Generated by Django 3.2.20 on 2023-07-28 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('distance_base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance_additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_multiplier_factor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waiting_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days_of_week', models.CharField(help_text='Comma-separated days (e.g., Mon,Tue)', max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PricingConfig',
        ),
        migrations.AddField(
            model_name='configurationchangelog',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing_app.pricingconfiguration'),
        ),
        migrations.AddField(
            model_name='configurationchangelog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
